name: python build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  python_build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: python_build_step1
      - uses: actions/checkout@v4
